services:
  main-service:
    build:
      context: ./main-service/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bloss_docker_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=12345678
      - RABBITMQ_JMS_URL=amqp://rabbitmq:5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=12345678
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./data:/app/data

  app-service:
    build:
      context: ./app-service/
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=12345678
      - RABBITMQ_JMS_URL=amqp://rabbitmq:5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=12345678
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=bloss_docker_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MAX_CONNECTIONS=300
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672" # веб-консоль RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=12345678
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/minio
    command: server ~/minio --console-address :9090
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  app-network:
    driver: bridge